export const browserCoreExamples = [
  "firstclaw browser status",
  "firstclaw browser start",
  "firstclaw browser stop",
  "firstclaw browser tabs",
  "firstclaw browser open https://example.com",
  "firstclaw browser focus abcd1234",
  "firstclaw browser close abcd1234",
  "firstclaw browser screenshot",
  "firstclaw browser screenshot --full-page",
  "firstclaw browser screenshot --ref 12",
  "firstclaw browser snapshot",
  "firstclaw browser snapshot --format aria --limit 200",
  "firstclaw browser snapshot --efficient",
  "firstclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "firstclaw browser navigate https://example.com",
  "firstclaw browser resize 1280 720",
  "firstclaw browser click 12 --double",
  'firstclaw browser type 23 "hello" --submit',
  "firstclaw browser press Enter",
  "firstclaw browser hover 44",
  "firstclaw browser drag 10 11",
  "firstclaw browser select 9 OptionA OptionB",
  "firstclaw browser upload /tmp/file.pdf",
  'firstclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "firstclaw browser dialog --accept",
  'firstclaw browser wait --text "Done"',
  "firstclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "firstclaw browser console --level error",
  "firstclaw browser pdf",
];
